### ISSUE TITLE
Application non-functional over SSH

### ISSUE THREAD

**Issue by parkerlreed** [and3rson/clay#36]
Using JuiceSSH on my phone for example, there's no way to get to the Settings tab. Alt modifier locks, but when I press 9 it just inputs "9"

EDIT: This may be related solely to JuiceSSH. Works fine when trying from a regular SSH client on computer.

**Comment by ValentijnvdBeek** [comment]
Hi Parker,

Thanks for the bug report, but I think it is a JuiceSSH issue. I just looked at it and I think that JuiceSSH is sending both keys separately which trips up urwid when you're too slow. Using the number keyboard works pretty well and is only iffy with the settings page or the debug page (which you rarely need). Even then, it works if you're quick enough.

Also if you don't mind not being able to search for songs using a number you can drop this into your ~/.config/clay/config.yaml which will make numbers switch pages.

```
hotkeys:
  mod_key: ctrl

  clay_hotkeys:
    global:
      seek_start: mod + q
      play_pause: mod + p
      seek_backward: shift + left
      seek_forward: shift + right
      quit: mod + x
      toggle_shuffle: mod + r
      next_song: mod + d
      prev_song: mod + a
      toggle_repeat_one: mod + o
      handle_escape: esc, mod + _
      show_debug: "0"
      show_library: "1"
      show_artists: "2"
      show_stations: "3"
      show_playlists: "4"
      show_search: "5"
      show_queue: "6"
      show_settings: "9"
```

I hope this helps.

ps. is it me or does [this look amazing](https://ibb.co/fzmsFU)?  
pps. for your use case it might be interesting to look at [an MPRIS2 controller](https://www.boumann.ch/amaroid/) when a release with #32 comes out or, if you feel like helping to test, on the porcelain branch.
